server:
  servlet:
    context-path: /auth
  port: 63020
spring:
  profiles:
    active: dev
  application:
    name: auth-service
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: Ov23liFJV9ZqNo62lxIo
            client-secret: 6ea42bf99ab6a70e457d91b761111855518a5c07