server:
  servlet:
    context-path: /auth
  port: 63020
spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:mysql://localhost:3306/code_runner_auth
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: Ov23liFJV9ZqNo62lxIo
            client-secret: 6ea42bf99ab6a70e457d91b761111855518a5c07
            redirect-uri:  http://localhost:63020/auth/oauth2/code/github
logging:
  level:
    org:
      springframework:
        security: trace